version: '3.9'

name: jerry-platform

networks:
  service_zone:
    driver: overlay
    attachable: true

services:
  nginx:
    networks:
      - service_zone
    image: tjdals9638/nginx:latest
    depends_on:
      - condition-frontend
      - condition-backend
    container_name: nginx
    extra_hosts:
      - "jerry-platform:121.151.25.182"
    ports:
    - "80:80"
    - "443:443"
    - "8001:8001"

  condition-frontend:
    networks:
      - service_zone
    image: tjdals9638/condition-frontend:latest
    container_name: condition-frontend
    depends_on:
      - condition-backend
    extra_hosts:
      - "jerry-platform:121.151.25.182"
    links:
      - condition-backend
    ports:
    - "3000:80"

  condition-backend:
    networks:
      - service_zone
    extra_hosts:
      - "jerry-platform:121.151.25.182"
    image: tjdals9638/condition-backend:latest
    container_name: condition-backend
    ports:
    - "8000:8000"
